pipeline {
    agent any
    stages {
        stage ('build hello world img'){
            steps{
                script{
                    sh 'docker build -t sgiriprasad/hello-world /Dockerfile'
                }
            }
        }
        stage ('push image to hub'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'dockerhubcred', variable: 'dockerpwd')]) {
                    sh 'docker login -u sgiriprasad -p ${dockerhubcred}'
                    }
                    sh 'docker push sgiriprasad/hello-world'
                }
            }
        }
    }
}