pipeline {
    agent any
    stages {
        stage ('build nice job img'){
            steps{
                script{
                    sh 'docker build -t sgiriprasad/nicejob app2/'
                }
            }
        }
        stage ('push image to hub'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'dockerhubcred', variable: 'dockerpwd')]) {
                    sh 'docker login -u sgiriprasad -p ${dockerpwd}'
                    }
                    sh 'docker push sgiriprasad/nicejob'
                }
            }
        }
    }
}